namespace: otus-hw-5-volodina
replicaCount: 1
image:
  repository: elenkavolodina/otus_hw5:v8
service:
  type: NodePort
  port: 8000
postgresql:
  enabled: true
  postgresqlUsername: root
  postgresqlPassword: root
  postgresqlDatabase: otus
  service:
    port: "5432"